version: '2.4'

services:
  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "8050:8000"
    env_file:
    - .env
    restart: always
  backend:
    image: ${BACKEND_IMAGE}
    ports:
      - "4050:5000"
    env.file:
      - .env
    restart: always